name: deploy-package
on:
  push:
    tags:
      - v*
jobs:
  package-actions:
    strategy:
      matrix:
        pyversion: ["3.9"]
    os: ["windows-latest"]
    # ["ubuntu-latest", "windows-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install latests stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyversion }}
      - name: Install packages
        run: pip install maturin
      - name: Deploy Package
        shell: bash
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: maturin publish -u $PYPI_USERNAME  -p $PYPI_PASSWORD -r https://test.pypi.org/simple
