name: Running Tests

on: [push]

jobs:
  running-discrust-core-tests:
    # strategy:
    #   matrix:
    #     pyversion: ["3.8", "3.9"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latests stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run cargo test on discrust_core
        run: cargo test -p discrust_core

  running-python-tests:
    strategy:
      matrix:
        pyversion: ["3.7", "3.8", "3.9"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latests stable Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.pyversion }}
      - name: Install Package
        run: pip install . pytest
      - name: Run Pytest
        run: pytest tests
